name: simple ci workflow
on:
  push:
    branches:
      - main
jobs:
  systembuild:
    runs-on: ubuntu-latest
    steps:
      - name: Print a test message
        run: echo "hello from $GITHUB_ACTOR"

